### ISSUE TITLE
Dockerfile must have FROM field

### ISSUE THREAD

**Issue by KalitaAlexey** [slicebuild/sb#23] opened 2015-10-26 19:38 UTC
I am trying to implement test command. Before it I tried to test via terminal. I do

```
sb fetch
sb make -f d
docker build -t sb-test <DIR_WITH_DOCKERFILE>
```

It errors

```
Sending build context to Docker daemon 188.9 kB
Step 0 : RUN export DEBIAN_FRONTEND=noninteractive && apt-get update -q -y && alias apt-get='apt-get --no-install-recommends' && apt-get install -q -y apt-utils
Please provide a source image with `from` prior to run
```

**Comment by alexro** [comment] 2015-10-27 16:49
Alex is still working on the formatters I think. Can you leave test command to him too?
There is something else in pipeline for you once I spec it out tonight :)

**Comment by KalitaAlexey** [comment] 2015-10-27 19:15
@alexro I did formatting. Did I make it wrong?

**Comment by alexro** [comment] 2015-10-28 02:37
There was an error in my docker formatter introduced 2 days ago, so maybe you looked at it and reproduced.

I now fixed the error and the dockerfile should be okay. Also needed to update because of the OS section removal.

**Closed as completed** 2015-11-01 15:33 UTC
